import { Device, LabRoom, AppNotification } from './types';

export const INITIAL_ROOMS: LabRoom[] = [
  { id: 'R1', nama: 'Labor Komputer 1', kode: 'LAB-INF-01', deskripsi: 'Laboratorium utama untuk pemrograman dan desain grafis', kapasitas: 36 },
  { id: 'R2', nama: 'Labor Komputer 2', kode: 'LAB-INF-02', deskripsi: 'Laboratorium untuk jaringan, OS, dan perakitan PC', kapasitas: 30 },
  { id: 'R3', nama: 'Labor Multimedia', kode: 'LAB-MM', deskripsi: 'Laboratorium multimedia dan pengembangan web', kapasitas: 24 },
  { id: 'R4', nama: 'Ruangan Server & Network', kode: 'LAB-SRV', deskripsi: 'Ruangan pusat server, router, dan kelistrikan laboratorium', kapasitas: 5 }
];

export const INITIAL_DEVICES: Device[] = [
  {
    id: 'D01',
    kodeInventaris: 'INV/LAB-01/LPT/2023/001',
    namaPerangkat: 'Asus ExpertBook B1400',
    jenisPerangkat: 'Laptop',
    merk: 'Asus',
    tipeModel: 'B1400CPE',
    nomorSeri: 'ASN4N0248593D',
    processor: 'Intel Core i5-1135G7',
    ram: '8 GB',
    jenisPenyimpanan: 'SSD',
    kapasitasPenyimpanan: '512 GB',
    tahunPembuatan: 2023,
    lokasiRuangan: 'Labor Komputer 1',
    kondisi: 'Baik',
    tanggalPembelian: '2023-04-12',
    sumberDana: 'Dana BOS',
    fotoPerangkat: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    catatanTambahan: 'Digunakan sebagai workstation asisten labor.',
    logs: [
      {
        id: 'L01',
        deviceId: 'D01',
        deviceName: 'Asus ExpertBook B1400',
        tanggalKerusakan: '2024-02-15',
        jenisKerusakan: 'Sistem operasi korup / tidak bisa boot',
        teknisi: 'Ahmad Jayadi, S.Kom.',
        tindakanPerbaikan: 'Re-install OS Windows 11 Pro dan update driver',
        statusPerbaikan: 'Selesai',
        biayaPerbaikan: 150000,
        tanggalPerbaikan: '2024-02-16'
      }
    ]
  },
  {
    id: 'D02',
    kodeInventaris: 'INV/LAB-01/LPT/2023/002',
    namaPerangkat: 'Asus ExpertBook B1400',
    jenisPerangkat: 'Laptop',
    merk: 'Asus',
    tipeModel: 'B1400CPE',
    nomorSeri: 'ASN4N0248598A',
    processor: 'Intel Core i5-1135G7',
    ram: '8 GB',
    jenisPenyimpanan: 'SSD',
    kapasitasPenyimpanan: '512 GB',
    tahunPembuatan: 2023,
    lokasiRuangan: 'Labor Komputer 1',
    kondisi: 'Rusak Ringan',
    keteranganKerusakan: 'Beberapa tombol keyboard (A, S, D, Enter) tidak merespon saat ditekan.',
    tanggalPembelian: '2023-04-12',
    sumberDana: 'Dana BOS',
    fotoPerangkat: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    catatanTambahan: 'Menunggu penggantian modul keyboard internal.',
    logs: [
      {
        id: 'L02',
        deviceId: 'D02',
        deviceName: 'Asus ExpertBook B1400',
        tanggalKerusakan: '2026-06-20',
        jenisKerusakan: 'Keyboard sebagian tidak berfungsi',
        teknisi: 'Hendra Saputra',
        tindakanPerbaikan: 'Pembersihan fleksibel keyboard, tetapi masih tidak berfungsi. Perlu ganti part.',
        statusPerbaikan: 'Dalam Proses',
        biayaPerbaikan: 0
      }
    ]
  },
  {
    id: 'D03',
    kodeInventaris: 'INV/LAB-02/LPT/2022/015',
    namaPerangkat: 'Lenovo ThinkPad L14 Gen 2',
    jenisPerangkat: 'Laptop',
    merk: 'Lenovo',
    tipeModel: 'ThinkPad L14',
    nomorSeri: 'PF2XG8K5',
    processor: 'AMD Ryzen 5 5650U',
    ram: '16 GB',
    jenisPenyimpanan: 'SSD',
    kapasitasPenyimpanan: '512 GB',
    tahunPembuatan: 2022,
    lokasiRuangan: 'Labor Komputer 2',
    kondisi: 'Baik',
    tanggalPembelian: '2022-08-20',
    sumberDana: 'Komite Sekolah',
    fotoPerangkat: 'https://images.unsplash.com/photo-1618424181497-157f25b6ddd5?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    catatanTambahan: 'Baterai masih tahan 4 jam pemakaian intensif.',
    logs: []
  },
  {
    id: 'D04',
    kodeInventaris: 'INV/LAB-01/PC/2024/001',
    namaPerangkat: 'PC Desktop Dell OptiPlex 3000',
    jenisPerangkat: 'Komputer Desktop',
    merk: 'Dell',
    tipeModel: 'OptiPlex 3000 Tower',
    nomorSeri: 'DELL-9X8C2B3',
    processor: 'Intel Core i5-12500',
    ram: '16 GB',
    jenisPenyimpanan: 'SSD',
    kapasitasPenyimpanan: '512 GB',
    tahunPembuatan: 2024,
    lokasiRuangan: 'Labor Komputer 1',
    kondisi: 'Baik',
    tanggalPembelian: '2024-01-10',
    sumberDana: 'Dana BOS',
    fotoPerangkat: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    catatanTambahan: 'Menggunakan monitor Dell 21.5 inci. Lengkap dengan UPS.',
    logs: []
  },
  {
    id: 'D05',
    kodeInventaris: 'INV/LAB-01/PC/2024/002',
    namaPerangkat: 'PC Desktop Dell OptiPlex 3000',
    jenisPerangkat: 'Komputer Desktop',
    merk: 'Dell',
    tipeModel: 'OptiPlex 3000 Tower',
    nomorSeri: 'DELL-9X8C2B4',
    processor: 'Intel Core i5-12500',
    ram: '16 GB',
    jenisPenyimpanan: 'SSD',
    kapasitasPenyimpanan: '512 GB',
    tahunPembuatan: 2024,
    lokasiRuangan: 'Labor Komputer 1',
    kondisi: 'Baik',
    tanggalPembelian: '2024-01-10',
    sumberDana: 'Dana BOS',
    fotoPerangkat: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    catatanTambahan: 'UPS terpasang.',
    logs: []
  },
  {
    id: 'D06',
    kodeInventaris: 'INV/LAB-02/PC/2021/045',
    namaPerangkat: 'PC Desktop HP ProDesk 400 G6',
    jenisPerangkat: 'Komputer Desktop',
    merk: 'HP',
    tipeModel: 'ProDesk 400 G6 MT',
    nomorSeri: 'HP-MCH04593B',
    processor: 'Intel Core i3-10100',
    ram: '8 GB',
    jenisPenyimpanan: 'HDD',
    kapasitasPenyimpanan: '1 TB',
    tahunPembuatan: 2021,
    lokasiRuangan: 'Labor Komputer 2',
    kondisi: 'Rusak Berat',
    keteranganKerusakan: 'Mati total. Diduga power supply terbakar akibat tegangan listrik tidak stabil dan merusak motherboard.',
    tanggalPembelian: '2021-11-05',
    sumberDana: 'APBD Provinsi',
    fotoPerangkat: 'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    catatanTambahan: 'Sudah diperiksa oleh teknisi eksternal, disarankan penggantian motherboard & PSU.',
    logs: [
      {
        id: 'L03',
        deviceId: 'D06',
        deviceName: 'PC Desktop HP ProDesk 400 G6',
        tanggalKerusakan: '2026-05-10',
        jenisKerusakan: 'Mati total, tercium bau gosong',
        teknisi: 'Ahmad Jayadi, S.Kom.',
        tindakanPerbaikan: 'Mendiagnosa kerusakan PSU dan jalur VRM motherboard. Pengajuan dana perbaikan diajukan ke kepala labor.',
        statusPerbaikan: 'Pending',
        biayaPerbaikan: 1200000
      }
    ]
  },
  {
    id: 'D07',
    kodeInventaris: 'INV/LAB-02/PC/2021/046',
    namaPerangkat: 'PC Desktop HP ProDesk 400 G6',
    jenisPerangkat: 'Komputer Desktop',
    merk: 'HP',
    tipeModel: 'ProDesk 400 G6 MT',
    nomorSeri: 'HP-MCH04593C',
    processor: 'Intel Core i3-10100',
    ram: '8 GB',
    jenisPenyimpanan: 'HDD',
    kapasitasPenyimpanan: '1 TB',
    tahunPembuatan: 2021,
    lokasiRuangan: 'Labor Komputer 2',
    kondisi: 'Baik',
    tanggalPembelian: '2021-11-05',
    sumberDana: 'APBD Provinsi',
    fotoPerangkat: 'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    catatanTambahan: 'Kondisi harddisk 98% sehat menurut sentinel.',
    logs: [
      {
        id: 'L04',
        deviceId: 'D07',
        deviceName: 'PC Desktop HP ProDesk 400 G6',
        tanggalKerusakan: '2024-09-02',
        jenisKerusakan: 'Fan bising dan PC sering mati sendiri (overheat)',
        teknisi: 'Hendra Saputra',
        tindakanPerbaikan: 'Pembersihan debu heatsink, penggantian thermal paste DeepCool Z5, dan ganti fan casing belakang.',
        statusPerbaikan: 'Selesai',
        biayaPerbaikan: 85000,
        tanggalPerbaikan: '2024-09-03'
      }
    ]
  },
  {
    id: 'D08',
    kodeInventaris: 'INV/LAB-MM/IFP/2024/001',
    namaPerangkat: 'Interactive Flat Panel ViewSonic 75"',
    jenisPerangkat: 'Interactive Flat Panel (IFP)',
    merk: 'ViewSonic',
    tipeModel: 'ViewBoard IFP7550-3',
    nomorSeri: 'VS-7550-IFP992A',
    processor: 'ARM Cortex A73 quad-core',
    ram: '4 GB',
    jenisPenyimpanan: 'None',
    kapasitasPenyimpanan: '32 GB eMMC',
    tahunPembuatan: 2024,
    lokasiRuangan: 'Labor Multimedia',
    kondisi: 'Baik',
    tanggalPembelian: '2024-05-18',
    sumberDana: 'Dana BOS',
    fotoPerangkat: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    catatanTambahan: 'Terpasang di dinding depan labor multimedia. Stylus pen lengkap 2 unit.',
    logs: []
  },
  {
    id: 'D09',
    kodeInventaris: 'INV/LAB-01/IFP/2025/002',
    namaPerangkat: 'Smart Screen Maxhub V6 Classic 65"',
    jenisPerangkat: 'Interactive Flat Panel (IFP)',
    merk: 'Maxhub',
    tipeModel: 'V6-C6530',
    nomorSeri: 'MXH-65C-202599',
    processor: 'Intel Core i5 (OPS Module)',
    ram: '16 GB',
    jenisPenyimpanan: 'SSD',
    kapasitasPenyimpanan: '256 GB',
    tahunPembuatan: 2025,
    lokasiRuangan: 'Labor Komputer 1',
    kondisi: 'Baik',
    tanggalPembelian: '2025-02-15',
    sumberDana: 'APBD Provinsi',
    fotoPerangkat: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    catatanTambahan: 'Dilengkapi modul OPS Windows 11 Pro. Kamera 48MP internal berfungsi normal.',
    logs: []
  },
  {
    id: 'D10',
    kodeInventaris: 'INV/SRV-NET/RTR/2023/001',
    namaPerangkat: 'MikroTik RB4011 iGS+RM Router',
    jenisPerangkat: 'Perangkat Jaringan',
    merk: 'MikroTik',
    tipeModel: 'RB4011iGS+RM',
    nomorSeri: 'MT-RB4011-8F29',
    processor: 'AL21400 4-cores 1.4GHz',
    ram: '1 GB',
    jenisPenyimpanan: 'None',
    kapasitasPenyimpanan: '512 MB NAND',
    tahunPembuatan: 2023,
    lokasiRuangan: 'Ruangan Server & Network',
    kondisi: 'Baik',
    tanggalPembelian: '2023-03-05',
    sumberDana: 'Komite Sekolah',
    fotoPerangkat: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    catatanTambahan: 'Routerboard utama pengatur bandwidth dan gateway internet SMAN 1 Teluk Kuantan.',
    logs: [
      {
        id: 'L05',
        deviceId: 'D10',
        deviceName: 'MikroTik RB4011 iGS+RM Router',
        tanggalKerusakan: '2024-11-12',
        jenisKerusakan: 'Hang total akibat overheat di rak server',
        teknisi: 'Ahmad Jayadi, S.Kom.',
        tindakanPerbaikan: 'Relokasi router ke bagian atas rak, penambahan kipas pendingin AC 220V di rak server.',
        statusPerbaikan: 'Selesai',
        biayaPerbaikan: 120000,
        tanggalPerbaikan: '2024-11-12'
      }
    ]
  },
  {
    id: 'D11',
    kodeInventaris: 'INV/SRV-NET/SWT/2022/012',
    namaPerangkat: 'Switch Manageable Cisco Catalyst 24 Port',
    jenisPerangkat: 'Perangkat Jaringan',
    merk: 'Cisco',
    tipeModel: 'WS-C2960+24TC-L',
    nomorSeri: 'FOC2203Y87B',
    processor: 'PowerPC 405',
    ram: '128 MB',
    jenisPenyimpanan: 'None',
    kapasitasPenyimpanan: '64 MB Flash',
    tahunPembuatan: 2022,
    lokasiRuangan: 'Ruangan Server & Network',
    kondisi: 'Baik',
    tanggalPembelian: '2022-06-18',
    sumberDana: 'APBD Provinsi',
    fotoPerangkat: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    catatanTambahan: 'Membagi VLAN untuk Labor 1, Labor 2, dan Lab Multimedia.',
    logs: []
  },
  {
    id: 'D12',
    kodeInventaris: 'INV/LAB-02/AP/2023/008',
    namaPerangkat: 'Ubiquiti UniFi AP AC Pro',
    jenisPerangkat: 'Perangkat Jaringan',
    merk: 'Ubiquiti',
    tipeModel: 'UniFi UAP-AC-PRO',
    nomorSeri: 'UBNT-ACPRO-91AA',
    processor: 'Atheros MIPS 74Kc',
    ram: '128 MB',
    jenisPenyimpanan: 'None',
    kapasitasPenyimpanan: '16 MB',
    tahunPembuatan: 2023,
    lokasiRuangan: 'Labor Komputer 2',
    kondisi: 'Rusak Ringan',
    keteranganKerusakan: 'Sinyal WiFi 2.4GHz sangat lemah dan sering putus-putus. Kecepatan drop.',
    tanggalPembelian: '2023-08-11',
    sumberDana: 'Dana BOS',
    fotoPerangkat: 'https://images.unsplash.com/photo-1600132806370-bf17e65e942f?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    catatanTambahan: 'Masih bisa menyala menggunakan kabel PoE. Frekuensi 5GHz normal.',
    logs: [
      {
        id: 'L06',
        deviceId: 'D12',
        deviceName: 'Ubiquiti UniFi AP AC Pro',
        tanggalKerusakan: '2026-06-15',
        jenisKerusakan: 'Sinyal 2.4GHz drop / tidak stabil',
        teknisi: 'Hendra Saputra',
        tindakanPerbaikan: 'Percobaan firmware upgrade dan reset konfigurasi. Gejala masih menetap, terindikasi masalah hardware pemancar.',
        statusPerbaikan: 'Dalam Proses',
        biayaPerbaikan: 0
      }
    ]
  },
  {
    id: 'D13',
    kodeInventaris: 'INV/LAB-MM/LPT/2024/005',
    namaPerangkat: 'Acer Aspire 5 Slim A515',
    jenisPerangkat: 'Laptop',
    merk: 'Acer',
    tipeModel: 'A515-58M-53Y3',
    nomorSeri: 'NXKHGSN00331',
    processor: 'Intel Core i5-1335U',
    ram: '16 GB',
    jenisPenyimpanan: 'SSD',
    kapasitasPenyimpanan: '512 GB',
    tahunPembuatan: 2024,
    lokasiRuangan: 'Labor Multimedia',
    kondisi: 'Baik',
    tanggalPembelian: '2024-07-30',
    sumberDana: 'Komite Sekolah',
    fotoPerangkat: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    catatanTambahan: 'Sangat baik untuk rendering video FHD ringan.',
    logs: []
  },
  {
    id: 'D14',
    kodeInventaris: 'INV/LAB-02/PC/2021/047',
    namaPerangkat: 'PC Desktop HP ProDesk 400 G6',
    jenisPerangkat: 'Komputer Desktop',
    merk: 'HP',
    tipeModel: 'ProDesk 400 G6 MT',
    nomorSeri: 'HP-MCH04593D',
    processor: 'Intel Core i3-10100',
    ram: '8 GB',
    jenisPenyimpanan: 'HDD',
    kapasitasPenyimpanan: '1 TB',
    tahunPembuatan: 2021,
    lokasiRuangan: 'Labor Komputer 2',
    kondisi: 'Baik',
    tanggalPembelian: '2021-11-05',
    sumberDana: 'APBD Provinsi',
    fotoPerangkat: 'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    catatanTambahan: 'Berfungsi dengan baik, OS Linux Ubuntu Desktop.',
    logs: []
  }
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'N01',
    title: 'Perangkat Rusak Berat',
    message: 'PC Desktop HP ProDesk 400 G6 (INV/LAB-02/PC/2021/046) dilaporkan Mati Total oleh teknisi.',
    type: 'error',
    date: '2026-06-28',
    read: false,
    deviceId: 'D06'
  },
  {
    id: 'N02',
    title: 'Keyboard Laptop Rusak',
    message: 'Asus ExpertBook B1400 (INV/LAB-01/LPT/2023/002) mengalami kerusakan keyboard dan sedang dalam perbaikan.',
    type: 'warning',
    date: '2026-06-26',
    read: false,
    deviceId: 'D02'
  },
  {
    id: 'N03',
    title: 'Perlu Perawatan Rutin',
    message: 'Ubiquiti UniFi AP AC Pro (INV/LAB-02/AP/2023/008) di Labor Komputer 2 terdeteksi mengalami penurunan sinyal frekuensi 2.4GHz.',
    type: 'info',
    date: '2026-06-25',
    read: true,
    deviceId: 'D12'
  },
  {
    id: 'N04',
    title: 'Pemeriksaan Berkala',
    message: 'Interactive Flat Panel ViewSonic di Labor Multimedia belum diperiksa dalam 30 hari terakhir. Harap lakukan verifikasi kelayakan layar.',
    type: 'info',
    date: '2026-06-24',
    read: false,
    deviceId: 'D08'
  }
];
